# Generated by Django 5.1.7 on 2025-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_class', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('file_path', models.FilePathField(path='/Users/chitlchow/GitHub/nurturing-reads-app/database')),
            ],
        ),
    ]
