# Generated by Django 5.1.7 on 2025-03-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_path',
            field=models.FilePathField(path='G:\\nurturing read\\nurturing-reads-app\\database_5'),
        ),
    ]
